### ISSUE TITLE
define saveChosenCourses in CourseLoader and implement it in XmlLoader

### ISSUE THREAD

**Issue by Lidkin5** [TechnionYP5777/Owl2#36] opened 2016-12-12 17:29 UTC

**Comment by leyaniv** [comment] 2016-12-12 23:12
@Lidkin5 
@kobybs 
Isn't it the same as #34 ?

**Comment by nikitadizhur** [comment] 2016-12-13 00:01
closed, because it's a duplicate of #34

**Closed by nikitadizhur** 2016-12-13 00:01 UTC
